// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC70hqK5pkPbPaYi7IdjqntIJhA7Mhsja4',
    appId: '1:954905463798:web:b59e936633144ca2f915d7',
    messagingSenderId: '954905463798',
    projectId: 'find-fiesta',
    authDomain: 'find-fiesta.firebaseapp.com',
    storageBucket: 'find-fiesta.appspot.com',
    measurementId: 'G-JHWTHMM44Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQlb5JaNGkSnESKsK_i7_T6j-_Hh-irg',
    appId: '1:954905463798:android:f2f17faba3f03a1af915d7',
    messagingSenderId: '954905463798',
    projectId: 'find-fiesta',
    storageBucket: 'find-fiesta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQTjBScMM7Zpjhroq3BzcJJ49sZGjxUM',
    appId: '1:954905463798:ios:e14eb6e66d9c7ea7f915d7',
    messagingSenderId: '954905463798',
    projectId: 'find-fiesta',
    storageBucket: 'find-fiesta.appspot.com',
    iosClientId: '954905463798-9akhgdqghro74mftren180jt15bsb6es.apps.googleusercontent.com',
    iosBundleId: 'com.malinowski.fiestaFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQTjBScMM7Zpjhroq3BzcJJ49sZGjxUM',
    appId: '1:954905463798:ios:e14eb6e66d9c7ea7f915d7',
    messagingSenderId: '954905463798',
    projectId: 'find-fiesta',
    storageBucket: 'find-fiesta.appspot.com',
    iosClientId: '954905463798-9akhgdqghro74mftren180jt15bsb6es.apps.googleusercontent.com',
    iosBundleId: 'com.malinowski.fiestaFinder',
  );
}
